# Generated by Django 4.1.3 on 2023-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('draft', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='movie/')),
                ('country', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('rejissr', models.CharField(blank=True, max_length=100, null=True)),
                ('ssenary', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('janr', models.CharField(blank=True, max_length=100, null=True)),
                ('v_rolyah', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
