# Generated by Django 4.1.3 on 2023-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url_trailer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='фильм вышел'),
        ),
    ]
