# Generated by Django 4.1.6 on 2023-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_categorynews_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('age', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='Фото')),
            ],
            options={
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='v_rolyah',
        ),
        migrations.AddField(
            model_name='movie',
            name='v_rolyah',
            field=models.ManyToManyField(blank=True, null=True, related_name='film_actor', to='movie.actors'),
        ),
    ]
