# Generated by Django 4.1.6 on 2023-02-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_actors_remove_movie_v_rolyah_movie_v_rolyah'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
