# Generated by Django 4.1.6 on 2023-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_contact_address_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url_trailer',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на трейлер'),
        ),
    ]
